include:
  - board: nice_nano
    shield: cradio_left nicehatharry nice_view_custom
  - board: nice_nano
    shield: cradio_right nicehatharry nice_view_custom
  - board: nice_nano
    shield: settings_reset
